### ISSUE TITLE
Don't quite understand this statement

### ISSUE THREAD

**Issue by RobLewis** [jdberry/tag#10]
Not sure exactly what you mean by this: 

• Tagnames may include spaces, but the entire tag list must be provided as one parameter: "a multiword tag name".

Do you mean that if any tag in the list contains a space, the entire list must be enclosed in double quotes? Or do you mean that each tag that contains a space must be individually quoted? 

It would be the difference between this: 
"tag1,tag2,tag3 with spaces,tag4"
and this: 
tag1,tag2,"tag3 with spaces",tag4

Or do you mean something else? Please clarify, and thanks for making this software!

**Comment by marcuserronius** [comment]
Those two examples are both correct, and will behave identically. The quotes are actually to make whatever shell you are using interpret the whole thing as a single argument (just like you already do with filenames that contain spaces). Also valid would be to escape spaces with backslashes:
`tag1,tag2,tag3\ with\ spaces,tag4`

**Comment by jdberry** [comment]
@marcuserronius's description is correct.
