### ISSUE TITLE
Getting OSStatus error -43 when calling tag from another script

### ISSUE THREAD

**Issue by andrewmudd** [jdberry/tag#11]
I'm trying to call tag from within another application, and when I do, it's dying with "The operation couldn't be completed. (OSStatus error -43.)". When I try to call tag from within a shell script, it throws the same error.

**Comment by jdberry** [comment]
@andrewmudd: can you provide a specific example of the parameters you are passing to tag that cause it to fail, and how and where you are calling it from?

**Comment by jdberry** [comment]
No response from @andrewmudd; closing issue.
