### ISSUE TITLE
adding directory scope for tag search

### ISSUE THREAD

**Issue by marcuserronius** [jdberry/tag#13]
The scope for the --find command, unless I am mistaken, can only be home, local, or volume. IIUC, the system call allows NSURLs as search scopes. Maybe this could be added into the tool? Perhaps something like `--scope /path/to/dir/`, or `tags --match --recursive <tags> <dir>...`
I think this might be more efficient than a shell glob when searching through thousands of files.
Thanks!

**Comment by marcuserronius** [comment]
So, the feature is already there. whoops. thought I had the most recent version; looks like the homebrew formula needs updating.

**Comment by jdberry** [comment]
@marcuserronius As I recall this is implemented in the code but perhaps not fully tested, and no release has been cut from it. If you can test and give feedback maybe I can cut a release. I think I was a bit worried that the existing meaning might change a little: I'm not sure, as it's been a few months since I made that change.

**Comment by marcuserronius** [comment]
been pretty busy the last few days... tested --find and --match with the extended options. --match worked perfectly, but --find acts strangely. First off, I don't think --enter and --descend apply to it, since it always does a recursive search. Secondly, --all does nothing. I can't make --find find dotfiles in any manner.

I'll try to fully test --set --add and --remove, but I suspect since --match is working properly, those will too.

**Comment by marcuserronius** [comment]
Fairly rigorous testing of `--add`, `--set` and `--remove` show them working perfectly.

**Comment by jdberry** [comment]
@marcuserronius: yes, --enter and --descend don't apply to find, as you observed, because it is searching across a volume already. And no, I don't think it applies to hidden files either, so I'm not sure I can make --all work for find.

**Comment by jdberry** [comment]
I added in v0.8 the ability to put explicit URL scopes around tag's find operations.

**Comment by jdberry** [comment]
Thanks for your testing! ;)
