### ISSUE TITLE
Cannot locate files with special characters in their paths

### ISSUE THREAD

**Issue by kakyoism** [jdberry/tag#15]
My environment: 
- OS X 10.10.3
- tag-0.7.5 from Homebrew

I tried to add tag to a file from Terminal this way:

    $ tag -l "/Users/me/Downloads/Virtual Barber Shop Hair Cut - 3D Sound (Amazingtag!!) (Low).mp4"

and here is the error messages:

    tag -l "/Users/me/Downloads/Virtual Barber Shop Hair Cut - 3D Sound (Amazingtagtag -l "/Users/me/Downloads/Virtual Barber Shop Hair Cut - 3D Sound (Amazingtag -h) (Low).mp4") (Low).mp4"
    -bash: syntax error near unexpected token `('

Looks like tag's argparse has problems with special characters in the path.
Please help.

**Comment by jdberry** [comment]
Note that the error you're seeing is coming from bash, before tag is even called. This will go away if you use single quotes to quote your string: bash is getting hung up on the exclamation points I believe.
