### ISSUE TITLE
Not working on R/W mounted NTFS Volume?

### ISSUE THREAD

**Issue by shivahoj** [jdberry/tag#16]
Hello, 
tag v0.8.1 doesnt seem to work on an external USB 4 Tbytes Harddisk, that is mounted R/W by Paragon NTFS v12.1.62.(Macbook pro, 10.10.3, tag installed via port)
It looks to me as if it doesnt even access the Volume, i hear no sound, and there is no delay, e.g. "tag --find '*'  --descend /Volumes/4T", and of course no matching files are output.
This is not a permissions issue, because in Finder i can create, edit and delete files(as well as  their tags) on said drive easily.
I should mention that cocatech's PathFinder 7.1.5 shows some strange behaviour too on NTFS Volumes (shows, but is unable to change tags).

Any idea on this ?
Any way to force a verbose/debug output or dump a logfile that i could send to you?

Yours
Dirk

**Comment by jdberry** [comment]
I suspect that the issue you're seeing is that the NTFS drive doesn't support metadata searches, and so the find operation is failing. If the FS does support tags, then you should be able to find tagged files using the match operation and --descend, but of course it will be slower.
