### ISSUE TITLE
Add limited support for OpenMeta

### ISSUE THREAD

**Issue by grahamperrin** [jdberry/tag#17]
Please: could you add an option to find tags that use the `com.apple.metadata:kMDItemOMUserTags` attribute?

If so, then would `tag` work (for that purpose) with Mountain Lion?

Thanks

**Comment by jdberry** [comment]
I don't really have any interest in making this work. It's possible that you could patch the code to swap out the metadata attribute that tag uses, in the case of an older OS, or perhaps if a particular command line flag is set. If you want to do this, and and submit a patch that's not too intrusive, I'd consider it.
