### ISSUE TITLE
Machine readable output

### ISSUE THREAD

**Issue by hanej** [jdberry/tag#22]
Could you add an option to the list argument that puts a delimiter between the file name and the tags?  It's a hassle to parse out the files and any tags that may exist.  Also if the file name is a directory could you append a trailing slash to the name so it's obvious what is a file and what isn't?  That would be greatly appreciated.

Very nice application by the way!

**Comment by hanej** [comment]
After some hex debugging I found the output to be tab delimited.  That should solve the main problem.  It would be nice if the directory could have a trailing slash though.  It would avoid the need for a file/directory check for each line of output.

**Comment by jdberry** [comment]
This doesn't seem like a huge priority to me, and changing the default format of displayed directories might break somebody else. It's certainly possible, however.
