### ISSUE TITLE
-H, -L, -R switches not recognized

### ISSUE THREAD

**Issue by Feuermurmel** [jdberry/tag#23]
The man page specifies that e.g. either `-H` or `--home` can be used to limit searching of tagged files:

```
        -H | --home         Find tagged files in user home directory
        -L | --local        Find tagged files in home + local filesystems
        -R | --network      Find tagged files in home + local + network filesystems
```

Using `--home` works as expected:

```
$ tag --home -f Green
[…]/Desktop/test
```

But using `--H` instead gives an error (while still providing results):

```
$ tag -H -f Green
tag: invalid option -- H
[…]/Desktop/test
```

Im using v0.8.1 installed via MacPorts.

**Comment by jdberry** [comment]
Indeed. It looks like I added those switches to the case statement but not into the accepted getopt_long characters. Thanks for the report.

**Comment by Feuermurmel** [comment]
Maybe it's worth noting, now that `-R` isn't actually part of the interface yet, that for a tool to change the attributes of file, `-R` is by convention used to say `act recursively`. Examples for that are `chown`, `chmod`, `chatter` or `ls`.

Maybe you could use `-R` for the shorthand of `--descend`. What do you think?

**Comment by jdberry** [comment]
I'm inclined to take your suggestion @Feuermurmel, and add -R as an alias for --descend. And I'm inclined to simply remove the -H -L -R flags as currently defined, requiring the long form for these parameters.
