### ISSUE TITLE
`tag --add` with an existing tag removes color information in Finder

### ISSUE THREAD

**Issue by jlb1234** [jdberry/tag#24]
If I use the command `tag --add "Important" myFile.docx`, it adds the tag "Important" to my file. However, the `tag` tool also seems to remove the color information for display in the Finder for this tag. So in this instance, the "Important" tag is by default marked with a red dot, now it isn't marked as such anywhere in the Finder which is quite annoying.

**Comment by jdberry** [comment]
@jlb1234 I can't replicate this.

I do the following:

1. Create a file
2. Add standard color tags to it in the Finder
3. Use tag to add the Important flag
4. The finder continues to display the color tags, and also the Important tag, as expected.
