### ISSUE TITLE
xargs: unterminated quote

### ISSUE THREAD

**Issue by matthew-groth** [jdberry/tag#28]
This is a very useful tool. Unfortunately, no matter what I do I can't pipe it to xargs. Something in the readme said to use -0. But although this clearly changes the format of the output, whether or not I have it I always only get `xargs: unterminated quote`.

In the meantime I will look for a workaround. If anyone can share how they process the raw output without xargs perhaps that could help me too.

**Comment by jdberry** [comment]
This seems to work ok for me:

`tag -0 -l | xargs -0 -L1 echo`

That's not a very useful example, but it demonstrates that tag is deliminating lines with \0.
