### ISSUE TITLE
Find tags on invisible files

### ISSUE THREAD

**Issue by matthew-groth** [jdberry/tag#29]
According to the readme:
`The --all, --enter, and --recursive options apply to --add, --remove, --set, --match, and --list`

I need to --find invisible tags. Is there a workaround for this?

**Comment by jdberry** [comment]
Can you clarify? What's an invisible tag? Do you mean a tag on an invisible file?

**Comment by matthew-groth** [comment]
Yes that is what I meant, sorry.

**Comment by jdberry** [comment]
@matthew-groth... see the answer to #25: it is the same issue. The metadata database doesn't index invisible files, but you can do a match to find them.

**Comment by matthew-groth** [comment]
I see. Though match is extremely slow compared to find, so it is not practical to use (since I'm searching my whole computer). Is there any way match can be made faster?
