### ISSUE TITLE
How can I tag all the files within a folder in just one command line?

### ISSUE THREAD

**Issue by Sylvaaiin** [jdberry/tag#35]
Hi,

I'm able to tag a specific file if I put its name it in the command line.

But what if I want to tag a bunch of files (or all the files) which are in the same folder without naming them one by one?

Thanks in advance for your help :)

Regards,
---
Sylvain

**Comment by jdberry** [comment]
You can recursively add tags to files in a directory. It would be probably be nice to support the feature in #30, which calls for supporting the ability to not apply changes to directories, perhaps something like a --no-dirs option.
