### ISSUE TITLE
is it possible to see which tags have been used more recently?

### ISSUE THREAD

**Issue by foice** [jdberry/tag#36]
Hi I would like to list tags of a set of files, possibly all the tagged files in my computer, and list these tags according to the date of last use.
I may assume that the last use corresponds to the latest modification time of files tagged with a given tag, but this is an assumption ... is the tagging "history" somehow accessible anywhere?

**Comment by jdberry** [comment]
There is no metadata associated with a tag that tells when it was last used. There are, as you say, various dates associated with access and modification of the file, but these don't necessarily correlate to use of the file via a tag or tags.

It would be possible to discover files that are tagged in some way or another, and then sort them via access date, though you can't do that directly via the tag tool. You could create a pipeline something like this to match files tagged with `atagname` and then sort them by access time, for instance:

 `tag -m atagname -0 | xargs -0 ls -tu`

**Comment by foice** [comment]
I was trying similar pipes, or two lines scripts to be a bit more refined, but the only way to go would be to access the tag-mtime. I have no experience with `xattr` but it does not seem to be part of the tag `com.apple.metadata:_kMDItemUserTags`. Is it conceivable to put a custom xattr onto the file when one add/delete/modify `com.apple.metadata:_kMDItemUserTags` ?

**Comment by jdberry** [comment]
Sorry, @foice, not really sure what you're asking there. If you know you're changing the tags on the file then yes, you could add some other tag or xattribute on the file to indicate that it's been changed, or even to store the date at which it's been changed. But that approach would assume you're controlling all access to the file, or don't care about monitoring other access to the file.

**Comment by foice** [comment]
Just to add some context. Adding keywords/tags to files is most useful when you give the same tag to files that are meant to be tagged in the same category. If you use variants such as `my-tag`, `my tag`, `MyTag`, and `my_tag` chances are that you will be less efficient to retrieve these files. My strategy to avoid variants is to keep a list of the tags that I use. One useful way to keep and use this list is to look at tags that have been used recently, so I can see that I have used recently `my tag` and I will use that instead of a variant that in that moment may make more sense to me. I hope this makes more clear what I am trying to achieve.
