### ISSUE TITLE
Feature idea: verbose output

### ISSUE THREAD

**Issue by BarryMode** [jdberry/tag#37]
I have been using [jdberry/tag](https://github.com/jdberry/tag) in a generated script, which has thousands of lines like this: `tag --set tag1,tag2 file`. It'd be nice if I could do something like `tag --verbose` so I can see what's going on. Otherwise, it runs silently, which is great, but it'd be nice to have some form of reference as to how much longer it has to go. If this is already possible, I apologize. I looked for it but I didn't see it.

**Comment by jdberry** [comment]
Depending on what you're doing, (find, match) there's not necessarily any explanation to be given about what's happening. i.e., for --find we don't get any status from the OS during the find operation, apart from the files found.

There is no --verbose support currently. I'm not sure exactly what would help you, but if you have ideas, feel free to present them.

**Comment by BarryMode** [comment]
It could say that a file had certain tags applied. But that’s not necessary anyway. Maybe I’ll just create a progress bar that shows how many lines have been executed and how many are remaining, which has nothing to do with this repo so closing is fine then.
