### ISSUE TITLE
question:  are Mac OS x tags portable?

### ISSUE THREAD

**Issue by fschwiet** [jdberry/tag#38]
I have some questions about how tags work in Mac OSx Finder.  Are tags written to the file somehow, or is it stored somewhere else in the system?  Can I see/edit the tags from other operating systems?  My concern is if the tags will stick and be available in other environments.

Forgive me for asking through a github issue.  I have not been able to find the answer for myself.  I was looking to use a command line application like this to organize some media, but first I wanted to check the limitations of the work.

**Comment by NewSwitcher** [comment]
/*
I have some questions about how tags work in Mac OSx Finder. Are tags written to the file somehow, or is it stored somewhere else in the system? Can I see/edit the tags from other operating systems? My concern is if the tags will stick and be available in other environments.

Sorry I have not been able to find the answer for myself. I was looking to use a command line application like this to organize some media, but first I wanted to check the limitations of it.
*/



---
[ Google Translate ]
---

Hello. Unfortunately I do not speak English. I'm not even sure I understood your question correctly. But I will try to answer ...
If I understand correctly, it's about the "tags" that are presented on GitHub: https://github.com/jdberry/tag/.

As I understand it, this program (tag) is designed to work only with the operating system macOS.
Probably it is just a layer for the macOS API.
In this case, the result of the program will be the same as the result of the actions of the user.

I always thought that the service information about tags, the position of folders and files on the Finder grid, etc. is stored in the .DS_Store file that is stored next to these files.
However, the experiment that I conducted specifically for you, showed that this is not so.

For the experiment, I used the "rhash" utility ver. 1.3.5 (installed by the Homebrew package manager).
...

...
/usr/local/Cellar/rhash/1.3.5/bin/rhash --sha512 --output /Users/*User*/Desktop/123/DSStore.hash.txt /Users/*User*/Desktop/123/.DS_Store

All work was done in the folder 123 on the Desktop and in other folders attached to it.
...

...
Testing was conducted on a computer with this configuration :
Mac Pro  6.1 Late 2013 | 3.7 GHz Quad-Core Intel Xeon E5 | 12 Gb 1866 MHz DDR3 ECC | 2x AMD FirePro D300 2 Gb GDDR5 | PCI-SSD 256 Gb (APFS) | macOS 10.13.3 (17D47) High Sierra


*** What the experiment showed :

1 - the service file /Users/*User*/Desktop/123/.DS_Store was changed (its checksum was changed) only when the position of the folders and files on the Finder grid changed, when deleting folders and when creating new folders (and files).

2 - When the tags were assigned and when they were canceled, the checksum did not change.

I'm very surprised at this !


Probably I did not take into account something in this experiment, you can try to conduct it yourself on your system.

But if I got the right results, it means that the tag information is stored somewhere else : for example
in the meta-information of the files and folders in the file system of the operating system macOS itself.

In this case it will be very difficult to use it from under other OS.

If I had to solve the problem of placing some information about files and directories, I would
created independently and then would use an additional hidden (system) file, whose name starts with a period (.)
In this file, I would put the information I needed with the "bash" script or "AppleScript" in a format that was convenient for me.
For example, I would call it ".MY_Tags" (by analogy with the regular ".DS_Store" file).
I do not rule out the option when the contents of this file would be represented by an XML or JSON structure.

Such a file would be visible from under any OS and the solution would be cross-platform.

The downside of this decision would be additional actions to keep this file up to date and
load (small) on the file system of the computer as a whole.

Plus, it would be possible to "get rid" of the Apple-specific file system and you could not be afraid that
assholes from Apple again change something.

Unfortunately, I do not have more exact information, as I am not a developer of the program "tag", but only
user.

Sincerely Vladimir Maksimov, Smolensk, from Russia.

---

**Comment by jdberry** [comment]
tag writes to the extended attributes present in the HFS and APFS file systems, and possibly other file systems hosted on MacOS that also support extended attributes in some way. As such, it's possible that such a file system, hosted on another OS, such as Linux or Windows, might be able to read and interpret the xattrs, if they support reading and writing this metadata.

Note, however, that neither HFS tags, nor the tag tool, are designed to be a portable solution: they are intended only for use on Mac OS systems.
