### ISSUE TITLE
Sort files by tag

### ISSUE THREAD

**Issue by archaik** [jdberry/tag#43]
Is there a way to list all files in a folder, separated by tag? For example:

**tag**
Name1
Name2
Name3
**tag**
Name1
Name2
Name3
Name4
**tag**
Name1
Name2

i know that    `tag -tgf \* /Some/Folder`   will show files in the folder with any tag.
i know that    `tag -tgf \*|grep '^    '|cut -c5-|sort -u`    will list all Finder tags

I would like to a combination of the two without having to call out each tag-
( `tag -tgf 'tagname' /Some/Folder` ) 

Is this possible, or maybe even with a small script? 

Thanks very much

**Comment by jdberry** [comment]
I don't anticipate adding any support for this.
