### ISSUE TITLE
list of all tags

### ISSUE THREAD

**Issue by mett96** [jdberry/tag#45]
I red all the readme and also the previous issues, but I didn't find a command that show a list of the tags used in the finder, in order to know which colors are associated to each tag (as the screenshot attached)

<img width="215" alt="image" src="https://user-images.githubusercontent.com/16799929/52178097-8208c280-27ca-11e9-9e7d-62ad2a95be84.png">

thanks

**Comment by markwk** [comment]
I am looking for a similar function too so I can reduce the code I have in this [files tracking script](https://gist.github.com/markwk/bd9e0b109110a943d32548291e91a241).

**Comment by jdberry** [comment]
@markwk: would it be sufficient if there was a command that could find the list of all tags used? Do you need the number of times each is used as well or can you generate that otherwise?

**Comment by jdberry** [comment]
@mett96: you don't really need to know the color for a tag, right, but you want to know the entire set of tags being used? The color of the tag is implied by the name.

**Comment by mett96** [comment]
> @mett96: you don't really need to know the color for a tag, right, but you want to know the entire set of tags being used? The color of the tag is implied by the name.

Yes I want to know the set of tags used in a folder or in all files. It is not necessary to know the color.

**Comment by markwk** [comment]
> @markwk: would it be sufficient if there was a command that could find the list of all tags used? Do you need the number of times each is used as well or can you generate that otherwise?

Just a list would be fine. I can then use that list to iterate over the commands to get numbers. Thanks!

**Comment by jdberry** [comment]
I added support for a new usage command in v0.10 0ca3240928284eb13c5d59719ed520c8f5978704.

**Comment by markwk** [comment]
thanks @jdberry! Can't wait to see this update in next homebrew release once that's available. Cheers.

**Comment by viethung0823** [comment]
@jdberry the usage command doesn't count 0 right? Is there anyway I can get all tags even their usage are 0?
