### ISSUE TITLE
How to copy tags from one file to another?

### ISSUE THREAD

**Issue by JurekR** [jdberry/tag#48]
Hi,

I would like to copy the tags set on one file to another file. I am a bit lost how to do it though... Maybe you could even add this functionality?

I did an automator action "encode to m4a 128kbit". But I would like to then copy the tags set for the wav file to the generated m4a file.

Very strange btw. that there are no tools from Apple. Finder tags seems to be super rudimentary a.k.a. almost useless.

**Comment by jdberry** [comment]
The tag tool doesn't support this. You might be able to do it by scripting with the `xattr` command. You might also be able to do it by scripting the `tag` tool, but I haven't played around with either.
