### ISSUE TITLE
Strange behaviour from `tag` 

### ISSUE THREAD

**Issue by haakonstorm** [jdberry/tag#54]
<img width="728" alt="Screenshot of iTerm2 (16-06-2020, 14-54-28)" src="https://user-images.githubusercontent.com/193781/84777047-624df500-afe1-11ea-8705-c8bb4d9d0998.png">

What can be the reason for this file, (`zshrc.zsh`) not appearing while having a matching tag?

**Comment by jdberry** [comment]
This may be a case of the metadata indexer in the system choosing for some reason not to index that file. What happens if you root the find in that particular folder `/Users/storm/Dropbox/Databaser/scripts/zenv`?, i.e., `tag -f scr /Users/storm/Dropbox/Databaser/scripts/zenv`? But it looks like it's also not being found by a recursive list? Hmm.

**Comment by haakonstorm** [comment]
### 1. `kMDItemFSInvisible=1` was irrelevant

Initially I thought this was related to `kMDItemFSInvisible=1`, but this appears irrelevant.

### 2. Hard linked files only

- I've only seen this related to *hard linked* files, e.g:

    ```bash
    link original_file hardlinked_file
    ```

### 3. `mdfind` and multiple files with identical *inode number*

- TIL `mdfind` will print *only **one*** of any *set of files with identical* *inode number -* when searching system-wide for a matching `kMDItemUserTags` entry.
- Same behaviour also when rooting the search in a particular folder, e.g:

    ```bash
    mdfind "kMDItemUserTags == 'scr'" -onlyin . 
    ```

    `mdfind` will return only **one** file from that folder matching the tag *`scr` - even though that folder contains both* './original' and './hardlinked' both tagged `*scr*`.

### 4. "fix/workaround" using `mdimport` to reimport

- TIL *reimporting* one of a set of hard linked files to the mds store appears to make `mdfind` consistently pick that "*last* *reimported*" file when multiple files share the same *inode*.

    ```bash
    mdimport -r hardlinked_file 
    ```

### 5. Why this matters / use cases?

- The *git bare repo* technique for managing dotfiles is usually done by rooting the bare repo in `~`.
- This is usually done so as to not have to symlink scattered config files/folders to some central place for then to place them under version control, but stuff you want under version control living deeper than `~` and/or in cases you use hard links. E.g: I use them to hard link files I often edit, in to a VSCode workspace folder.

Now that we have a way to deterministically choose a particular from the set of hard linked files to be returned, the present behaviour of `mdfind`/`tag` is actually pretty nice. 

- At least in my use case - it's preferable to get only that one result as opposed to the alternative, getting the entire set of files with the same inode. I guess it would be desireable to have that option too, at least for corner cases like this.

I didn't test *symlinks,* or macOS "shortcuts".

**Comment by haakonstorm** [comment]
(This issue can be closed, unless you want to dig deeper. I'd be happy to assist/test. Thanks a lot for `tag`! On an unrelated note: using `tag` to somehow return files _without_ that tag, out of a set of files. I'm doing this currently with a separate script filter, but increasingly I'd love for this to be native to `tag`.)
